import Darwin
import XCTest
import OhMailEngine
@testable import OhMailKit

/// THE ENGINE-BACKED SOURCE, TESTED AGAINST BYTES NOBODY WROTE BY HAND.
///
/// Two halves, and they answer different questions.
///
///  1. **The corpus.** `Tests/Fixtures/wire/` holds the actual responses a live engine gave for one
///     journey against a real IMAP server. They are RECORDED rather than authored, by a generator
///     that lives with the engine and that fails if they ever stop matching what the engine emits.
///     Every decoder and projection assertion below reads those files. A hand-written fixture would
///     only prove that this file and the decoder agree with each other.
///
///     **The engine is not part of this repository, and neither is the recording, so these skip
///     when the corpus is absent.** A checkout of the client alone has no engine to record from —
///     the ordinary case for anyone reading this — and a green run against fixtures nobody
///     generated would be worth less than a skip.
///
///  2. **The live journey.** The real engine, spawned as a child process against GreenMail, with a
///     SECOND, INDEPENDENT IMAP CLIENT — the raw-socket one at the bottom of this file — checking
///     the server rather than asking the code under test where it put things. Organize-in-place
///     means the folder on the user's own mailbox is the fact, and `\Seen` on the server is the
///     fact, and nothing in the projection is evidence for either.
///
/// The live half SKIPS when there is no engine to run. A checkout of the client alone has none,
/// which is the ordinary case for anyone reading this; a skip is honest, and a green run against a
/// missing engine would not be.
@MainActor
final class EngineProjectionTests: XCTestCase {

    // MARK: - The corpus

    /// `apps/macos/Tests/Fixtures/wire`, built from components rather than written as one path.
    private static var corpusDirectory: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()      // OhMailKitTests
            .deletingLastPathComponent()      // Tests
            .appendingPathComponent("Fixtures")
            .appendingPathComponent("wire")
    }

    /// The recorded response for one route, or a SKIP when this checkout has no recording.
    ///
    /// A skip rather than a failure, for the same reason the live journey below skips without an
    /// engine: the corpus is produced by running a real engine against a real IMAP server, and a
    /// checkout that has neither cannot produce one. What must never happen is this suite going
    /// green against fixtures somebody wrote by hand, which is why there is no fallback here.
    private func corpus(_ name: String) throws -> Data {
        let url = Self.corpusDirectory.appendingPathComponent("\(name).json")
        guard let data = FileManager.default.contents(atPath: url.path) else {
            throw XCTSkip("no recorded engine responses in \(Self.corpusDirectory.lastPathComponent)/ "
                          + "— these are generated by running the engine against a real mail server")
        }
        return data
    }

    private func syncPage(_ name: String) throws -> WireSyncResponse {
        try JSONDecoder().decode(WireSyncResponse.self, from: try corpus(name))
    }

    /// The mirror the shell would be holding after one drain of a recorded page.
    private func mirror(_ name: String) throws -> EngineProjection {
        var projection = EngineProjection()
        projection.apply(try syncPage(name))
        return projection
    }

    /// Fixed, so every display time below is a statement about the projection rather than about
    /// when the suite happened to run. Chosen inside the corpus's own day.
    private static let now = Date(timeIntervalSince1970: 1_767_225_600)   // 2026-01-01T00:00:00Z

    // The three messages the recorded journey put on the server, by the ids the corpus carries.
    private static let kilnID = "00000000-0000-4000-8000-000000000004"
    private static let followUpID = "00000000-0000-4000-8000-000000000006"
    private static let firstContactID = "00000000-0000-4000-8000-000000000008"

    // MARK: - Decoding what the engine actually sent

    func testEveryRecordedResponseDecodes() throws {
        // Every `try` is hoisted out of the assertions on purpose. `XCTAssertEqual(try …)` CATCHES
        // what its autoclosure throws and records it as a failure — including an `XCTSkip`, which
        // turns "there is no recording in this checkout" into eight red tests that look like bugs.
        let mirrored = try mirror("sync-first-contact")
        XCTAssertEqual(mirrored.messages.count, 3)

        let names = ((try? FileManager.default.contentsOfDirectory(atPath: Self.corpusDirectory.path)) ?? [])
            .filter { $0.hasSuffix(".json") && $0 != "manifest.json" }
        XCTAssertFalse(names.isEmpty, "the recorded corpus is empty — the generator has never run")

        let body = try JSONDecoder().decode(WireBody.self, from: try corpus("message-body"))
        XCTAssertEqual(body.text, "Hello — we have not met before. I am writing about the pottery studio.")
        let marked = try JSONDecoder().decode(WireMarkSeenResult.self, from: try corpus("mark-seen"))
        XCTAssertEqual(marked.items.count, 1)
        let mailboxes = try JSONDecoder().decode(WireMailboxList.self, from: try corpus("mailboxes"))
        XCTAssertEqual(mailboxes.items.first?.provider, "imap")
    }

    /// Deltas are applied in the account's own order, not bucket by bucket.
    ///
    /// The recorded first drain interleaves: create at 2, move at 3, create at 5, move at 6. Reading
    /// the buckets in turn would apply every create after every move, and on a page where one
    /// message was both moved and then updated that is a message silently back to unread.
    func testDeltasAreOrderedByTheAccountsOwnSequenceAndNotByBucket() throws {
        let page = try syncPage("sync-after-mark-seen")
        let seqs = page.ordered.map(\.seq)
        XCTAssertEqual(seqs, seqs.sorted(), "the deltas were not handed over in seq order")

        // Not merely sorted — actually interleaved, so this is a real ordering rather than one
        // bucket that happened to come first.
        let buckets = Set(page.creates.map(\.seq)).union(page.moves.map(\.seq))
        XCTAssertGreaterThan(buckets.count, 2)
        XCTAssertNotEqual(seqs, page.creates.map(\.seq) + page.updates.map(\.seq)
                          + page.moves.map(\.seq) + page.deletes.map(\.seq),
                          "bucket order and seq order are the same here, so this pins nothing")
    }

    // MARK: - The Screener, as the shell would draw it

    func testFirstContactIsProjectedIntoTheScreenerGroupedBySender() throws {
        let (world, index) = try mirror("sync-first-contact")
            .world(bodies: [:], identity: EngineIdentity(address: "reader@corpus.test"), now: Self.now)

        XCTAssertEqual(world.waiting.map(\.addr), ["studio@pottery.test", "stranger@nowhere.test"],
                       "waiting senders are not newest-first, one row per sender")
        XCTAssertTrue(world.ohbox.isEmpty, "held mail reached the Ohbox")
        XCTAssertTrue(world.reads.isEmpty)
        XCTAssertTrue(world.receipts.isEmpty)

        // NO-COLLAPSE: the sender with two held messages carries both, in full, oldest first.
        let stranger = try XCTUnwrap(world.waiting.first { $0.addr == "stranger@nowhere.test" })
        XCTAssertEqual(stranger.held.count, 2)
        XCTAssertEqual(stranger.held.all.map(\.subj), ["Can we talk?", "Following up"],
                       "held mail is not oldest-first, or one of it was dropped")
        XCTAssertEqual(stranger.initial, "S")

        // The representative id is the one `POST /screener/:id` resolves — the NEWEST held message.
        XCTAssertEqual(stranger.id, Self.followUpID)
        XCTAssertEqual(index.waiting.first { $0.key == "stranger@nowhere.test" }?.heldIDs,
                       [Self.firstContactID, Self.followUpID])
        XCTAssertTrue(index.unplacedIDs.isEmpty)
    }

    /// The mark-seen the journey performed is visible in the very next drain — from the engine's
    /// bytes, not from a local edit.
    func testTheRecordedMarkSeenIsVisibleInTheNextDrain() throws {
        let before = try mirror("sync-first-contact")
            .world(bodies: [:], identity: EngineIdentity(), now: Self.now)
        let after = try mirror("sync-after-mark-seen")
            .world(bodies: [:], identity: EngineIdentity(), now: Self.now)

        let stranger = { (w: MailWorld) in w.waiting.first { $0.addr == "stranger@nowhere.test" }! }
        XCTAssertEqual(stranger(before.world).held.all.first { $0.id == Self.firstContactID }?.seen, false)
        XCTAssertEqual(stranger(after.world).held.all.first { $0.id == Self.firstContactID }?.seen, true,
                       "the message the journey marked seen still reads as unread")
        XCTAssertEqual(after.index.unreadByID[Self.firstContactID], false)
        XCTAssertEqual(after.index.unreadByID[Self.kilnID], true,
                       "a message the batch never named came back seen")
    }

    // MARK: - Bodies arrive later than headers

    func testABodyThatWasNeverFetchedIsNotAnEmptyMessage() throws {
        let projection = try mirror("sync-first-contact")
        let (world, _) = projection.world(bodies: [:], identity: EngineIdentity(), now: Self.now)
        let held = try XCTUnwrap(world.waiting
            .first { $0.addr == "stranger@nowhere.test" }?.held.all.first { $0.id == Self.firstContactID })

        XCTAssertNil(held.body, "an unfetched body rendered as text")
        XCTAssertEqual(held.content.preview,
                       "Hello — we have not met before. I am writing about the pottery studio.",
                       "the row lost the server's own preview line")

        // …and once it is in hand, the projection carries the whole text rather than the preview.
        let body = try JSONDecoder().decode(WireBody.self, from: try corpus("message-body"))
        let hydrated = projection.world(bodies: [Self.firstContactID: .available(body.text)],
                                        identity: EngineIdentity(), now: Self.now).world
        let full = try XCTUnwrap(hydrated.waiting
            .first { $0.addr == "stranger@nowhere.test" }?.held.all.first { $0.id == Self.firstContactID })
        XCTAssertEqual(full.body, body.text)
    }

    /// A message that lands in a stream carries a `BodyState` in the world, and `.notFetched` is
    /// what "we have not asked" looks like — never an empty string.
    func testStreamBodiesStartUnfetchedRatherThanEmpty() throws {
        let page = try perturbed("sync-first-contact") { message in
            message["folder"] = "ohmail/Reads"
        }
        var projection = EngineProjection()
        projection.apply(page)
        let (world, _) = projection.world(bodies: [:], identity: EngineIdentity(), now: Self.now)

        XCTAssertEqual(world.reads.count, 3)
        for message in world.reads {
            XCTAssertEqual(world.readsBodies[message.id], .notFetched)
            XCTAssertNil(world.readsBodies[message.id]?.text)
            XCTAssertNil(message.body, "a stream row claimed a body it never fetched")
        }
    }

    // MARK: - States a fixture set does not have

    /// A folder this build has never heard of must not take a page of mail down with it.
    func testAnUnknownFolderIsExcludedRatherThanFatal() throws {
        let page = try perturbed("sync-first-contact") { message in
            if message["id"] as? String == Self.kilnID { message["folder"] = "Archive/2026/Q1" }
        }
        var projection = EngineProjection()
        projection.apply(page)
        XCTAssertEqual(projection.messages.count, 3, "one unknown folder lost the whole page")

        let (world, index) = projection.world(bodies: [:], identity: EngineIdentity(), now: Self.now)
        XCTAssertEqual(index.unplacedIDs, [Self.kilnID])
        XCTAssertEqual(world.waiting.map(\.addr), ["stranger@nowhere.test"])
        XCTAssertTrue(world.ohbox.isEmpty, "unplaced mail was filed into a view it does not belong in")
    }

    /// The protected class cannot carry plaintext, and it is the constructor that enforces it.
    ///
    /// **BOTH ROWS, and that is not belt-and-braces.** The projection builds two different kinds of
    /// row from the same wire message — a `HeldMail` at the gate and a `Message` in a view — through
    /// two different functions, and the first version of this test exercised only the first. A
    /// mutation that deleted the sensitivity check in the second one passed it. The message a
    /// verification code is most likely to be sitting in is a stream, which is the branch that was
    /// not covered.
    func testProtectedMailCarriesNoContentAtAnyDepth() throws {
        func project(into folder: String) throws -> MailWorld {
            let page = try perturbed("sync-first-contact") { message in
                guard message["id"] as? String == Self.firstContactID else { return }
                message["sensitivity"] = ["sensitive": true, "category": "otp",
                                          "no_ai": true, "no_forward": true, "no_kb": true, "priority": false]
                message["folder"] = folder
            }
            var projection = EngineProjection()
            projection.apply(page)
            // A body already in hand, so this is about what the projection REFUSES to carry rather
            // than about what it happens not to have.
            return projection.world(bodies: [Self.firstContactID: .available("123456")],
                                    identity: EngineIdentity(), now: Self.now).world
        }

        let atTheGate = try project(into: "ohmail/Screener")
        let held = try XCTUnwrap(atTheGate.waiting
            .first { $0.addr == "stranger@nowhere.test" }?.held.all.first { $0.id == Self.firstContactID })
        XCTAssertTrue(held.isProtected)
        XCTAssertNil(held.body, "a protected held message carried a body")
        XCTAssertNil(held.content.preview, "a protected held message carried the server's preview line")
        XCTAssertNil(held.content.searchableText, "a protected held message reached the search index")

        let inAStream = try project(into: "ohmail/Reads")
        let row = try XCTUnwrap(inAStream.reads.first { $0.id == Self.firstContactID })
        XCTAssertTrue(row.isProtected, "a protected message in a stream was built as ordinary mail")
        XCTAssertNil(row.body, "a protected message carried a body")
        XCTAssertNil(row.preview, "a protected message carried the server's preview line")
        XCTAssertTrue(row.searchableText.isEmpty, "a protected message reached the search index")
        XCTAssertNotNil(row.sensitive, "the row lost the fact that it is protected")
    }

    /// A refusal arrives as the engine's own sentence, not as a status code, and never as an empty
    /// mailbox.
    func testTheEnginesRefusalIsReadAndRepeatedVerbatim() throws {
        let failure = EngineSource.failure(status: 401, body: try corpus("unauthorized"))
        XCTAssertEqual(failure.kind, .authentication)
        XCTAssertEqual(failure.reason, "authentication required",
                       "the engine's own sentence was replaced with a generic one")
        XCTAssertFalse(failure.isRetryable)
    }

    /// Nothing this source does can be taken back yet, so nothing it returns may offer an Undo.
    func testNoIntentFromThisSourceOffersAnUndoItWouldHaveToWithdraw() async {
        let source = EngineSource(requester: RefusingRequester(), token: Secret("t"))
        let outcome = source.apply(.markSeen(message: Self.firstContactID))
        guard case .applied(let ack) = outcome else { return XCTFail("mark-seen was refused outright") }
        XCTAssertNil(ack.receipt, "an Undo was offered for something that cannot be reversed")

        guard case .refused(let failure) = source.apply(.reverse(Receipt(id: "never-happened"))) else {
            return XCTFail("an unknown receipt was accepted")
        }
        XCTAssertEqual(failure.kind, .unsupported)
        XCTAssertFalse(failure.reason.isEmpty)
        await source.settle()
    }

    /// An intent with no wire is refused out loud. Doing nothing quietly leaves a control that
    /// looks like it works.
    func testIntentsWithNoWireAreRefusedWithAReason() {
        let source = EngineSource(requester: RefusingRequester(), token: Secret("t"))
        for intent in [MailIntent.setTag(message: "m", tag: .pottery, on: true),
                       .addVIP("someone@example.test"),
                       .saveDraft(message: "m", text: "hello")] {
            guard case .refused(let failure) = source.apply(intent) else {
                return XCTFail("\(intent) was accepted by a source that cannot perform it")
            }
            XCTAssertEqual(failure.kind, .unsupported)
            XCTAssertTrue(failure.reason.contains("not connected to your mailbox"),
                          "the refusal did not say what was not done: \(failure.reason)")
        }
    }

    // MARK: - Perturbing recorded bytes

    /// Recorded engine bytes with ONE field changed, so a state the journey did not reach is still
    /// tested against a real payload rather than against something written here.
    ///
    /// The alternative — a hand-written `/sync` page — is what this whole file exists to avoid: it
    /// would pin the decoder to this author's reading of the protocol instead of to the engine's.
    private func perturbed(_ name: String,
                           _ edit: (inout [String: Any]) -> Void) throws -> WireSyncResponse {
        let recorded = try corpus(name)
        var root = try XCTUnwrap(try JSONSerialization.jsonObject(with: recorded) as? [String: Any])
        var changes = try XCTUnwrap(root["changes"] as? [String: Any])
        for bucket in ["creates", "updates", "moves", "deletes"] {
            let list = (changes[bucket] as? [[String: Any]]) ?? []
            changes[bucket] = list.map { change -> [String: Any] in
                guard var entity = change["entity"] as? [String: Any], change["type"] as? String == "message" else {
                    return change
                }
                edit(&entity)
                var copy = change
                copy["entity"] = entity
                return copy
            }
        }
        root["changes"] = changes
        return try JSONDecoder().decode(WireSyncResponse.self,
                                        from: try JSONSerialization.data(withJSONObject: root))
    }

    /// A transport that answers nothing, for the cases that must not reach one.
    private struct RefusingRequester: EngineRequesting {
        func send(_ request: URLRequest) async throws -> (HTTPURLResponse, Data) {
            throw EngineTransportError.unavailable("no engine in this test")
        }
    }

    // MARK: - The live journey

    /// FIRST CONTACT, END TO END, WITH THE SERVER AS THE PROOF.
    ///
    /// A stranger writes to a GreenMail mailbox. The real engine — the same `main.ts` the shipped
    /// app spawns — connects, ensures the `ohmail/*` tree and files the message. This shell reads
    /// it through `EngineSource` and renders it in the Screener. Then one write: mark it seen, and
    /// check the flag on the server with a second IMAP client, because the projection agreeing with
    /// itself is not evidence that anything reached the mailbox.
    func testTheLiveMailboxIsReadFiledAndWrittenTo() async throws {
        let live = try LiveEngine.start(self)
        defer { live.stop() }

        // ── A stranger writes, appended by a client that is not the code under test.
        let messageID = "live-first-contact-\(UUID().uuidString)@stranger.test"
        let probe = try IMAPProbe(host: LiveEngine.imapHost, port: LiveEngine.imapPort)
        defer { probe.close() }
        try probe.login(user: live.user, password: LiveEngine.password)
        try probe.append(mailbox: "INBOX", message: """
        Message-ID: <\(messageID)>\r
        From: stranger@nowhere.test\r
        To: \(live.user)\r
        Subject: Can we talk?\r
        Date: Mon, 03 Aug 2026 08:14:00 +0000\r
        Content-Type: text/plain; charset=utf-8\r
        \r
        Hello — we have not met before.
        """)

        // ── The shell attaches to the running engine and reads the world whole.
        let source = EngineSource(requester: live.transport, token: live.token)
        let shell = RecordingSink()
        let state = source.start(sink: shell)
        guard case .syncing = state else {
            return XCTFail("a source with a mailbox behind it reported \(state) before it had read anything")
        }

        var waiting: WaitingSender?
        for _ in 0..<60 {
            await source.settle()
            waiting = shell.world.waiting.first { $0.addr == "stranger@nowhere.test" }
            if waiting != nil { break }
            try await Task.sleep(nanoseconds: 1_000_000_000)
            await source.refresh()
        }
        let sender = try XCTUnwrap(waiting, "the Screener never showed the message the engine filed")
        XCTAssertEqual(sender.held.count, 1)
        XCTAssertEqual(sender.held.first.subj, "Can we talk?")
        XCTAssertFalse(sender.held.first.seen)

        // ── THE SERVER IS THE PROOF. The message has physically moved out of INBOX and into a real
        //    folder any other mail client can see — checked by the second client, not by asking the
        //    code under test where it put it.
        let screenerUIDs = try probe.uids(in: "ohmail.Screener", messageID: messageID)
        XCTAssertEqual(screenerUIDs.count, 1, "the message is not in ohmail/Screener on the server")
        let inboxUIDs = try probe.uids(in: "INBOX", messageID: messageID)
        XCTAssertTrue(inboxUIDs.isEmpty, "the message is still in INBOX — nothing was organized")

        // ── The one write. `affected` is the mailbox's answer, from its own response.
        let messageId = sender.held.first.id
        guard case .applied(let first) = await source.perform(.markSeen(message: messageId)) else {
            return XCTFail("the engine refused the only write this slice performs")
        }
        XCTAssertEqual(first.affected, 1, "the engine reported that nothing moved")
        XCTAssertNil(first.receipt, "an Undo was offered for a write that cannot be taken back")

        // ── `\Seen` ON THE SERVER. The API writes desired state; the engine's own cycle puts the
        //    flag on the real mailbox, so this waits for a cycle rather than for the projection.
        var flags: [String] = []
        for _ in 0..<60 {
            flags = try probe.flags(in: "ohmail.Screener", uid: screenerUIDs[0])
            if flags.contains("\\Seen") { break }
            try await Task.sleep(nanoseconds: 1_000_000_000)
        }
        XCTAssertTrue(flags.contains("\\Seen"),
                      "the second IMAP client does not see \\Seen on the server: \(flags)")

        // ── Marking an already-seen message seen moves nothing, and the ZERO comes back from the
        //    engine rather than from a local belief about it.
        guard case .applied(let again) = await source.perform(.markSeen(message: messageId)) else {
            return XCTFail("a repeat mark-seen was refused")
        }
        XCTAssertEqual(again.affected, 0,
                       "the engine reported a change for a message that was already seen")

        // ── And a body only arrives when it is asked for.
        XCTAssertEqual(source.bodyState(for: messageId, in: .ohbox), .notFetched)
        source.requestBody(for: messageId, in: .ohbox)
        await source.settle()
        XCTAssertEqual(source.bodyState(for: messageId, in: .ohbox).text,
                       "Hello — we have not met before.")
    }
}

// MARK: - The shell, recorded

@MainActor
private final class RecordingSink: MailSourceSink {
    var world = MailWorld()
    var syncStates: [SyncState] = []
    var bodies: [String: BodyState] = [:]

    func worldDidChange(_ world: MailWorld) { self.world = world }
    func bodyDidChange(id: String, in place: Place, to state: BodyState) { bodies[id] = state }
    func syncStateDidChange(_ state: SyncState) { syncStates.append(state) }
}

// MARK: - The real engine, as a child process

/// Spawns the engine the shipped app spawns, pointed at GreenMail.
///
/// It runs the engine's SOURCE through `tsx` rather than a compiled bundle, because that is how the
/// engine actually runs today: the compiled entry point cannot resolve its own sync loop and exits.
/// `OHMAIL_TEST_ENGINE` names the entry point; without it this looks for one in the surrounding
/// workspace and skips if there is none.
@MainActor
private struct LiveEngine {
    let engine: EngineProcess
    let transport: EngineTransport
    let token: Secret
    let user: String
    let directory: URL

    static let imapHost = "127.0.0.1"
    static let imapPort: UInt16 = 3143
    static let password = "test"

    /// Variables the ENGINE reads. They go into this process's environment because `plan` composes
    /// only the data directory and the key — everything else is inherited by the child.
    private static var installed: [String] = []

    static func start(_ test: XCTestCase) throws -> LiveEngine {
        let entry = try engineEntry()
        let root = entry.deletingLastPathComponent()      // src
            .deletingLastPathComponent()                  // sidecar
            .deletingLastPathComponent()                  // apps
            .deletingLastPathComponent()                  // the workspace
        guard FileManager.default.fileExists(atPath: root.appendingPathComponent("node_modules/tsx").path) else {
            throw XCTSkip("the workspace's node dependencies are not installed, so the engine cannot start")
        }
        guard reachable(host: imapHost, port: imapPort) else {
            throw XCTSkip("no IMAP server on \(imapHost):\(imapPort) — start it with `docker compose up -d greenmail`")
        }

        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("ohmail-engine-source-\(UUID().uuidString.prefix(8))")
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)

        // A fresh GreenMail user per run → a mailbox nothing else has touched.
        let user = "t-\(UUID().uuidString.lowercased())@trafficflow.test"
        let mailbox = [
            "OHMAIL_IMAP_HOST": imapHost,
            "OHMAIL_IMAP_PORT": String(imapPort),
            "OHMAIL_IMAP_USER": user,
            "OHMAIL_IMAP_PASS": password,
            "OHMAIL_IMAP_SECURE": "0",
            "OHMAIL_MAILBOX_ADDRESS": user,
            // Short, because the flag the write asks for reaches the real server on a sync cycle
            // and this test waits for one rather than for a projection.
            "OHMAIL_POLL_MS": "1000",
            "CI": "true",
        ]
        for (name, value) in mailbox { setenv(name, value, 1) }
        installed = Array(mailbox.keys)

        let wrapper = directory.appendingPathComponent(ENGINE_FILE_STEM)
        try Data("""
        #!/bin/sh
        cd "\(root.path)"
        exec "\(try nodePath())" --import tsx "\(entry.path)"

        """.utf8).write(to: wrapper)
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: wrapper.path)

        var environment = ProcessInfo.processInfo.environment
        environment[ENGINE_PATH_VAR] = wrapper.path
        environment[KEK_VAR] = String(repeating: "0", count: 64)
        environment[DATA_DIR_VAR] = directory.path

        let plan = EngineProcess.plan(environment: environment,
                                      executableDirectory: directory,
                                      dataDirectoryFallback: directory)
        guard case .spawn(let launch) = plan else {
            throw Live("the plan refused to start the engine: \(plan)")
        }
        let engine = EngineProcess(launch: launch)
        let transport = EngineTransport(engine: engine)
        engine.start()

        // Generous: a first launch builds the on-disk mirror and runs every migration.
        let deadline = Date().addingTimeInterval(180)
        while Date() < deadline {
            if case .serving = engine.status { break }
            if case .failed(let why, _) = engine.status {
                engine.stop()
                throw Live("the engine did not start: \(why)")
            }
            usleep(100_000)
        }
        guard case .serving = engine.status, let ready = engine.ready else {
            engine.stop()
            throw Live("the engine never reached serving: \(engine.status)")
        }
        return LiveEngine(engine: engine, transport: transport, token: ready.sessionToken,
                          user: user, directory: directory)
    }

    func stop() {
        engine.stop()
        for name in LiveEngine.installed { unsetenv(name) }
        LiveEngine.installed = []
        try? FileManager.default.removeItem(at: directory)
    }

    private static func engineEntry() throws -> URL {
        if let named = ProcessInfo.processInfo.environment["OHMAIL_TEST_ENGINE"] {
            let url = URL(fileURLWithPath: named)
            guard FileManager.default.fileExists(atPath: url.path) else {
                throw XCTSkip("OHMAIL_TEST_ENGINE names \(named), and there is nothing there")
            }
            return url
        }
        let workspace = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()   // OhMailKitTests
            .deletingLastPathComponent()   // Tests
            .deletingLastPathComponent()   // the client
            .deletingLastPathComponent()   // apps
            .deletingLastPathComponent()   // the workspace
        let entry = ["apps", "sidecar", "src", "main.ts"].reduce(workspace) { $0.appendingPathComponent($1) }
        guard FileManager.default.fileExists(atPath: entry.path) else {
            throw XCTSkip("no engine at \(entry.path); set OHMAIL_TEST_ENGINE to run this against one")
        }
        return entry
    }

    private static func nodePath() throws -> String {
        for candidate in ["/usr/local/bin/node", "/opt/homebrew/bin/node", "/usr/bin/node"]
        where FileManager.default.isExecutableFile(atPath: candidate) {
            return candidate
        }
        let which = Process()
        which.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        which.arguments = ["which", "node"]
        let pipe = Pipe()
        which.standardOutput = pipe
        try which.run()
        which.waitUntilExit()
        let found = String(decoding: pipe.fileHandleForReading.readDataToEndOfFile(), as: UTF8.self)
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard !found.isEmpty else { throw XCTSkip("no node on this machine, so the engine cannot run") }
        return found
    }

    private static func reachable(host: String, port: UInt16) -> Bool {
        guard let probe = try? IMAPProbe(host: host, port: port) else { return false }
        probe.close()
        return true
    }

    struct Live: Error, CustomStringConvertible {
        let description: String
        init(_ description: String) { self.description = description }
    }
}

// MARK: - A second, independent IMAP client

/// **THE CLIENT THAT IS NOT THE CODE UNDER TEST.**
///
/// Organize-in-place means the organization is not a row in a database, it is where the message
/// physically sits in the user's mailbox — so the only assertion worth making about a move or a
/// flag is one made by something that shares no code with the thing that made it. This is a
/// deliberately small IMAP client: a socket, line reads, and the four commands the assertions need.
///
/// It is POSIX sockets rather than `URLSession` or `Network.framework` on purpose. The shipped
/// binary is checked for links against CFNetwork, Network and Security, and that check is what
/// keeps the download's "no network code" disclosure honest; a test-only client that linked one of
/// them would put the framework in the package's build graph for no reason. Nothing here links
/// anything.
private final class IMAPProbe {
    private var fd: Int32
    private var buffer = Data()
    private var counter = 0

    init(host: String, port: UInt16) throws {
        fd = socket(AF_INET, SOCK_STREAM, 0)
        guard fd >= 0 else { throw Probe("no socket") }
        var address = sockaddr_in()
        address.sin_family = sa_family_t(AF_INET)
        address.sin_port = port.bigEndian
        guard inet_pton(AF_INET, host, &address.sin_addr) == 1 else {
            close(); throw Probe("\(host) is not an address")
        }
        // A read that never returns would hang the whole suite with no clue why.
        var timeout = timeval(tv_sec: 20, tv_usec: 0)
        setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &timeout, socklen_t(MemoryLayout<timeval>.size))
        setsockopt(fd, SOL_SOCKET, SO_SNDTIMEO, &timeout, socklen_t(MemoryLayout<timeval>.size))

        let connected = withUnsafePointer(to: &address) { pointer in
            pointer.withMemoryRebound(to: sockaddr.self, capacity: 1) { generic in
                connect(fd, generic, socklen_t(MemoryLayout<sockaddr_in>.size))
            }
        }
        guard connected == 0 else { close(); throw Probe("could not reach \(host):\(port)") }
        _ = try line()      // the greeting
    }

    func close() {
        if fd >= 0 { _ = Darwin.close(fd) }
        fd = -1
    }

    func login(user: String, password: String) throws {
        _ = try command("LOGIN \"\(user)\" \"\(password)\"")
    }

    func append(mailbox: String, message: String) throws {
        let payload = message.replacingOccurrences(of: "\r\n", with: "\n")
            .replacingOccurrences(of: "\n", with: "\r\n")
        _ = try command("APPEND \(mailbox) {\(payload.utf8.count)}", literal: payload)
    }

    /// The UIDs of a message in a folder, found by its `Message-ID` header. Empty when it is not
    /// there — which is exactly the assertion "it left INBOX" needs.
    func uids(in mailbox: String, messageID: String) throws -> [Int] {
        _ = try command("SELECT \(mailbox)")
        let lines = try command("UID SEARCH HEADER Message-ID \"<\(messageID)>\"")
        for line in lines where line.uppercased().hasPrefix("* SEARCH") {
            return line.dropFirst("* SEARCH".count).split(separator: " ").compactMap { Int($0) }
        }
        return []
    }

    /// The flags the SERVER holds for a message. `\Seen` here is the only `\Seen` that counts.
    func flags(in mailbox: String, uid: Int) throws -> [String] {
        _ = try command("SELECT \(mailbox)")
        let lines = try command("UID FETCH \(uid) (FLAGS)")
        for line in lines where line.contains("FLAGS (") {
            guard let start = line.range(of: "FLAGS ("),
                  let end = line.range(of: ")", range: start.upperBound..<line.endIndex) else { continue }
            return line[start.upperBound..<end.lowerBound]
                .split(separator: " ").map(String.init)
        }
        return []
    }

    /// Run one command and return every untagged line it produced. Throws on `NO`/`BAD`, so a
    /// server refusal is never mistaken for an empty result.
    @discardableResult
    private func command(_ text: String, literal: String? = nil) throws -> [String] {
        counter += 1
        let tag = "p\(counter)"
        try write("\(tag) \(text)\r\n")
        var untagged: [String] = []
        while true {
            let line = try self.line()
            if line.hasPrefix("+ ") || line == "+" {
                guard let literal else { throw Probe("the server asked for a literal and there was none") }
                try write(literal + "\r\n")
                continue
            }
            if line.hasPrefix("\(tag) ") {
                let rest = line.dropFirst(tag.count + 1)
                guard rest.hasPrefix("OK") else { throw Probe("\(text) → \(rest)") }
                return untagged
            }
            untagged.append(line)
        }
    }

    private func write(_ text: String) throws {
        var bytes = Array(text.utf8)
        var sent = 0
        while sent < bytes.count {
            let n = bytes.withUnsafeBytes { raw in
                Darwin.write(fd, raw.baseAddress!.advanced(by: sent), bytes.count - sent)
            }
            guard n > 0 else { throw Probe("the connection closed while writing") }
            sent += n
        }
    }

    private func line() throws -> String {
        while true {
            if let range = buffer.range(of: Data("\r\n".utf8)) {
                let line = buffer.subdata(in: buffer.startIndex..<range.lowerBound)
                buffer.removeSubrange(buffer.startIndex..<range.upperBound)
                return String(decoding: line, as: UTF8.self)
            }
            var chunk = [UInt8](repeating: 0, count: 4096)
            let n = read(fd, &chunk, chunk.count)
            guard n > 0 else { throw Probe("the connection closed while reading") }
            buffer.append(contentsOf: chunk[0..<n])
        }
    }

    struct Probe: Error, CustomStringConvertible {
        let description: String
        init(_ description: String) { self.description = description }
    }
}
